/* Copyright (c) 2018-2019, The Linux Foundation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#define CONFIG_PINCTRL_WCD 1
#define CONFIG_AUDIO_EXT_CLK 1
#define CONFIG_SND_SOC_WCD9XXX_V2 1
#define CONFIG_SND_SOC_WCD_MBHC 1
#define CONFIG_SND_SOC_WSA881X 1
#define CONFIG_SND_SOC_WCD9360 1
#define CONFIG_SND_SOC_WCD_DSP_MGR 1
#define CONFIG_SND_SOC_WCD_SPI 1
#define CONFIG_SND_SOC_WCD934X 1
#define CONFIG_SND_SOC_WCD934X_MBHC 1
#define CONFIG_SND_SOC_WCD934X_DSD 1
#define CONFIG_SND_SOC_WCD_CPE 1
#define CONFIG_WCD9XXX_CODEC_CORE 1
#define CONFIG_MSM_CDC_PINCTRL 1
#define CONFIG_MSM_QDSP6V2_CODECS 1
#define CONFIG_MSM_ULTRASOUND 1
#define CONFIG_MSM_QDSP6_APRV2_RPMSG 1
#define CONFIG_SND_SOC_MSM_QDSP6V2_INTF 1
#define CONFIG_MSM_ADSP_LOADER 1
#define CONFIG_REGMAP_SWR 1
#define CONFIG_MSM_QDSP6_SSR 1
#define CONFIG_MSM_QDSP6_PDR 1
#define CONFIG_MSM_QDSP6_NOTIFIER 1
#define CONFIG_SND_SOC_MSM_HOSTLESS_PCM 1
#define CONFIG_SND_SOC_SM8150 1
#define CONFIG_MSM_GLINK_SPI_XPRT 1
#define CONFIG_WCD_DSP_GLINK 1
#define CONFIG_SOUNDWIRE 1
#define CONFIG_SOUNDWIRE_WCD_CTRL 1
#define CONFIG_SND_SOC_WCD_MBHC_ADC 1
#define CONFIG_SND_SOC_QDSP6V2 1
#define CONFIG_QTI_PP 1
#define CONFIG_SND_HWDEP_ROUTING 1
#define CONFIG_DTS_EAGLE 1
#define CONFIG_DOLBY_DS2 1
#define CONFIG_DOLBY_LICENSE 1
#define CONFIG_DTS_SRS_TM 1
#define CONFIG_SND_SOC_MSM_STUB 1
#define CONFIG_MSM_AVTIMER 1
#define CONFIG_SND_SOC_MSM_HDMI_CODEC_RX 1
#define CONFIG_VOICE_MHI 1
#define CONFIG_SND_LGE_DTS 1
#if !defined(CONFIG_MACH_SM8150_MH2LM)
#define CONFIG_SND_SOC_TFA9872 1
#endif
#if defined(CONFIG_MACH_SM8150_MH2LM)
#define CONFIG_SND_SOC_CS35L41 1
#define CONFIG_SND_SOC_HSDET_L_SWITCH 1
#endif
#if defined(CONFIG_MACH_SM8150_MH2LM_SB_JP)
#define CONFIG_SND_USE_MBHC_EXTN_CABLE 1
#endif
#define CONFIG_SND_LGE_TX_NXP_LIB 1
#define CONFIG_MACH_LGE 1
#if !defined(CONFIG_MACH_SM8150_BETA)
#define CONFIG_SND_SOC_ES9218P 1
#define CONFIG_SND_SOC_LGE_ESS_DIGITAL_FILTER 1
#endif
#define CONFIG_SND_FM_RX_MI2S 1
#ifdef CONFIG_MACH_SM8150_FLASH
#define CONFIG_MACH_SM8150_FLASH 1
#define CONFIG_SND_SOC_TFA9872_STEREO 1
#endif
#if defined(CONFIG_MACH_SM8150_BETA)
#define CONFIG_SND_SOC_TFA9872_STEREO 1
#endif
#ifdef CONFIG_MACH_SM8150_ALPHA
#define CONFIG_MACH_SM8150_ALPHA 1
#define CONFIG_SND_SOC_SMA6101 1
//#define CONFIG_SND_SOC_CS43131 1
#endif
//#define CONFIG_QCOM_FSA4480_I2C 1
#define CONFIG_SND_LGE_MQA 1
#define CONFIG_SND_LGE_MABL 1
#define CONFIG_SND_LGE_CROSSTALK 1
#define CONFIG_SND_LGE_STEREO_SPEAKER 1
#define CONFIG_SND_LGE_DSDP_DUAL_AUDIO 1
#define CONFIG_SND_LGE_WDSP_SSR 1
