#
# Makefile for nfc devices
#

#obj-$(CONFIG_NFC_PN553_DEVICES)		+= pn553.o
obj-$(CONFIG_LGE_NFC_PN553)             += pn553_lge.o
obj-$(CONFIG_LGE_NFC_PN553)	+= pn553_lge_hwadapter.o
ccflags-$(CONFIG_NFC_PN553_DEVICES) := -DDEBUG

