#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_STM_FTM4)	+= touch_ftm4.o
obj-$(CONFIG_LGE_TOUCH_STM_FTM4)	+= touch_ftm4_prd.o

